#!/usr/bin/env bash
# Script that pings an IP address 5 times or shows usage if no IP is given

# Check if an argument (IP address) is provided
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"
